### ISSUE TITLE
Angle h and theta

### ISSUE THREAD

**Issue by p-zander** [p-zander/CP-tu-dortmund#1]
In src/01 in Funktion T(2?,  with derivative) h  ist converted to radians before adding it to theta, which remains in degree. The angle theta is then converted to radians within the function E. This doesn't make any sense. The variable h should rather be added to theta without converting it.

**Comment by p-zander** [comment]
Ausserdem is mein Akku leer

**Comment by p-zander** [comment]
Closing after commit?

**Comment by hassec** [comment]
didn't want to push for just a slight change, since its not a major error and the correctness of the resulting values shouldn't be affected.
